name: adb_connector
description: ADB Wireless Connector for macOS
version: 1.0.1+2
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  desktop_drop: ^0.7.1
  file_picker: ^11.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
